on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret plain
        id: plain
        run: echo '::set-output name=SECRET_PLAIN:add-mask::value'

      - name: Set secret from var
        id: var
        run: |
          FOO=bar
          echo "::set-output name=SECRET_VAR::add-mask::$FOO" >> $GITHUB_ENV

      - name: Use secrets
        run: |
          echo Plain: ${{ steps.plain.outputs.SECRET_PLAIN }}
          echo Var: ${{ steps.plain.outputs.SECRET_VAR }}
