on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret plain
        id: plain
        run: echo 'This is secret - ::add-mask::value'

      - name: Set secret from var
        id: var
        run: |
          FOO=bar
          echo "This is secret - ::add-mask::$FOO"

      - name: Use secrets
        run: |
          echo Plain: ${{ steps.plain.outputs.SECRET_PLAIN }}
          echo Var: ${{ steps.plain.outputs.SECRET_VAR }}
