on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret plain
        id: plain
        run: echo SECRET_PLAIN='::add-mask::value' >> $GITHUB_ENV

      - name: Set secret from var
        id: var
        run: |
          FOO=bar
          echo SECRET_VAR="::add-mask::$FOO" >> $GITHUB_ENV

      - name: Use secrets
        run: |
          echo Plain: ${{ env.SECRET_PLAIN }}
          echo Var: ${{ env.SECRET_VAR }}
