on:
  workflow_dispatch:
  push:
    branches:
      - main
  issues:
    types:
      - opened

jobs:
  run_sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running the sample
        uses: ./.github/actions/sample-action